### PR TITLE
Remove un-needed killing of parent process on stop

### PR DESCRIPTION
**Pull request by andrewgee**
I cannot understand why service manager is killing the parent process. On my system, when starting a process, it is being started with upstart as the parent process. When stopping the service it's killing the parent process which kills upstart and then my X session. This ruins my day :(

### CODE REVIEW

**Comment by HolyHaddock** [comment]
That is a nuisance!

I believe the reason it kills the parent process, is that with some combination of OS / sbt version, the jvm running the service gets forked, so if you don't kill the ppid, the parent sbt process just ended up loitering around not doing much.
Thought there was a check for accidentally killing pid 1 though?

**Comment by tenochdlc** [comment]
upstart is not always pid 1, that's the problem

**Comment by andrewgee** [comment]
Do we know if this jvm forking always means that `sbt` will be the parent process? If so, I'll put a check in to ensure that the parent process is `sbt` before killing, rather than the current pid 1 check?

**Comment by vaughansharman** [comment]
See smprocess.py, function "_is_system_or_smserver_or_test_process"

it does checks such as:

    if _is_pytest_process(pid):
        return True

to avoid killing important processes. Simply pu in a chack there that returns true if the process is upstart and sm will not kill the process on you

**Comment by andrewgee** [comment]
@vaughansharman: Thanks. I'll change my fork later on.

**Comment by andrewgee** [comment]
I still feel that this should perhaps be the opposite check though, and be checking for the one condition that requires the parent pid to be killed, rather than avoiding the init/upstart parents. Each system could have different parent pids. For example, what happens on Mac?

**Comment by vaughansharman** [comment]
Possibly, but as far as I am aware (bear in mind I no longer work there) you are the first person to experience this specific issue. So for now the simple solution should be sufficient. A more elegant solution may be required if this becomes a more widespread issue but it may be a bazooka for a fly at the moment

**Comment by tenochdlc** [comment]
I don't think it is necessary to kill the parent process, once the java process is detached, the parent process becomes pid=1 (or another upstart instance on Ubuntu), this is what the process tree looks like on my machine:

      `-lightdm,1727 --session-child 12 15
          |-{gdbus},1728
          `-upstart,1735,user1 --user
              |-java,2980 -Duser.dir=/var/tmp/auth_LOCAL/auth 

I suspect on MacOS is similar.

On CYGWIN the bash process that started the JVM stays around suspended, in fact there are two bash process that stay around.

At least on Linux, CYGWIN and native Windows (I haven't tested this on MacOS), once the child process terminates all parent processes terminate as well.

**Comment by vaughansharman** [comment]
I believe the parent pid killing is specifically related to sbt as mentioned by @HolyHaddock above

Removing this will possibly break a lot of people so be careful of flow on effects if you decide to significantly change how it works

**Comment by andrewgee** [comment]
Added upstart check. Might as well be a simple solution for now.

**Comment by tenochdlc** [comment]
sbt terminates and disappears from the process tree once the child java process is running and has been detached.
This is just standard process creation. If the process that started java stays around after java has terminated, there is a different problem.

**Comment by andrewgee** [comment]
Does anyone know who has experienced the problem that caused the ppid killing?

**Comment by tenochdlc** [comment]
I have, since I started using SM more than a year ago. After a new install I always just go and comment out the kill ppid.
I modified SM to work on CYGWIN and native windows and I do the same, no kill ppid.

**Comment by HolyHaddock** [comment]
Would be good to squash those three commits.

I'll try and dig in a bit over the weekend, as it does seem odd that the sbt parent process wouldn't die when its child java process died. 

Who's in charge of maintaining service-manager nowadays?

**Comment by andrewgee** [comment]
Closing this PR because I messed up the rebase somehow.

**Comment by agilestevesmith** [comment]
PR #42 has been merged, so servicemanager 0.3.0 does not kill the parent process unnecessarily

**Pull request closed without merging**
