### PR TITLE
Refactor and fix tests

### PR DESCRIPTION
**Pull request by ollyw**
## Included in the PR
1. Fixes the failing integration tests on Travis, which worked on OS X, but failed on Linux due to the differences in the way that the shell operates. These tests have been changed to remove the need for executing the shell directly.
2. Refactors the tests into a logical structure with a more cohesive set of tests per file
3. Removes the hardcoding of wait times and introduces a new feature to wait until service(s) have stopped. Once this has proven to work for tests, I believe it should be used in a more widespread fashion (e.g. in everybody's build processes). I have not made it the default behaviour. Previously the tests sometimes left services running without any notice, and added race conditions
4. Abstracted a test base class, which means that common functionality is kept in a single place
5. Reduces the test run time from ~160 seconds to ~70 seconds.
6. Adds test markers to tests which download source online (which can take long while as the service manager repo is getting big >100MB). The markers allow the online tests to be excluded. In the future, perhaps a different repo should be used so people don't use 100s of MB per test run.
## Caveats
1. This is very much an MVP. There are plenty of refactoring that could and should be done, but I believe this commit at least makes further refactoring approachable. The biggest future change would be to remove the stopping and starting of fake nexus per test and do it once for the integration tests.
2. There are lots of commits, and I am happy to squash on your advice.
3. I had to start refactoring even to see what the tests were attempting to do, so I am sorry to say that the refactoring and test fixing go hand in hand.
4. I was very much learning Python whilst doing this, may vary from best practice. I am very open to feedback about improving the code.
5. Has very much been done out of hours.

### CODE REVIEW

**Comment by ollyw** [comment]
@rpowis, @charleskubicek Is this PR something you would be interested in? :-)

**Comment by rpowis** [comment]
@ollyw Nice! We're very interested in this and have been meaning to make movements in this direction for a while, so thanks for making a start 👍 

> There are lots of commits
That's for sure 😉

I'd recommend splitting this out into a few PRs with more focus but I can advise on what should be chunked when I get some time to look over it all properly.

Stay tuned...

**Comment by ollyw** [comment]
@rpowis have you had any thoughts on how you would like to progress? I can make it happen.

Ultimately the majority of code change is splitting up, fixing and refactoring the tests. It would be of dubious value to change the tests incrementally, but I could split out the changes that affect the production code into a small number of commits, and then a whopper test refactor commit. The main downside to that is that the tests were broken in two or three different ways, so some PRs might not pass the unit tests if split up.

Which ever way I do it, there will be the same amount of code to review though :-)

**Comment by ollyw** [comment]
@rpowis @beyond-code-github I have rebased onto the latest changes in master. The tests pass

**Comment by tmikus** [comment]
@ollyw, @rpowis Are we planning to merge that in? I have some more improvements (Windows support) which would fit well after this one goes in.

**Comment by jakobgrunig** [comment]
Conflicts have been resolved and changes merged as part of PR #76

**Pull request closed without merging**
