### PR TITLE
Smstatus from psutil

### PR DESCRIPTION
**Pull request by HolyHaddock**
An alternative to https://github.com/hmrc/service-manager/pull/21 - should only call out to the process table once, and then do an O(Processes*Services) check to see what's running.

This seems to speed it up considerably locally, but it might be worth parallelising the search too.

### CODE REVIEW

**Comment by vaughansharman** [comment]
Nice work! getting a couple of test failing on my machine but that may just be my machine is no longer set up right, i'll try have a look tomorrow and we can try get a release out early next week with your changes :)

**Comment by HolyHaddock** [comment]
Ah, if they're failing for you too, I'll take another look.

**Comment by HolyHaddock** [comment]
Ah yes, python default variables are bound when the function's created, not each time it's called.

**Comment by vaughansharman** [comment]
All running now, looks good, I am no longer in the HMRC group so cant merge into master for you, I think its reasonable for you to do (given it has now been reviewed) I can release on pip for you

**Comment by HolyHaddock** [comment]
Thanks! Merged. :)

**Pull request closed without merging**
